// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    tenant_id,
    user_id,
    total_cents,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, user_id, total_cents, status, created_at, updated_at, deleted_at
`

type CreateOrderParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	UserID     string             `json:"user_id"`
	TotalCents int64              `json:"total_cents"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TotalCents,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    tenant_id,
    product_name,
    quantity,
    unit_price_cents,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, tenant_id, product_name, quantity, unit_price_cents, created_at
`

type CreateOrderItemParams struct {
	ID             string             `json:"id"`
	OrderID        string             `json:"order_id"`
	TenantID       string             `json:"tenant_id"`
	ProductName    string             `json:"product_name"`
	Quantity       int32              `json:"quantity"`
	UnitPriceCents int64              `json:"unit_price_cents"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.TenantID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.CreatedAt,
	)
	var i OrderItems
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TenantID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, tenant_id, user_id, total_cents, status, created_at, updated_at, deleted_at FROM orders
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetOrderByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.ID, arg.TenantID)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, tenant_id, product_name, quantity, unit_price_cents, created_at FROM order_items
WHERE order_id = $1 AND tenant_id = $2
ORDER BY created_at ASC
`

type ListOrderItemsParams struct {
	OrderID  string `json:"order_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItems, error) {
	rows, err := q.db.Query(ctx, listOrderItems, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItems
	for rows.Next() {
		var i OrderItems
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TenantID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $3, updated_at = $4
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, user_id, total_cents, status, created_at, updated_at, deleted_at
`

type UpdateOrderStatusParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TotalCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
