// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (Users, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (Users, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]Users, error)
}

var _ Querier = (*Queries)(nil)
